In [1]:
import os, sys
sys.path.append(os.path.join(os.getcwd(), "..")) #  so we can import from parent folder

In [22]:
import matplotlib.pyplot as plt
from scipy.optimize import least_squares
import numpy as np

from printer import latex_reaction_network_to_ode_system
from reaction_network.michaelis_menten import MichaelisMensenReactionNetwork

plt.rcParams.update({'font.size': 12})


In [23]:
# generate random rate params and integrate system
params = np.random.rand(3)*5
network = MichaelisMensenReactionNetwork(params)
solution = network.solve_ivp([0, 1, 0, 1], max_t=20)
# add random noise and drop complex C density, as it is not measurable
error_sigma = 0.02
data = np.abs(solution.y + np.random.normal(0, error_sigma, solution.y.shape))
data = np.delete(data, 2, axis=0)

In [24]:
def f(k):
    network = MichaelisMensenReactionNetwork(k)
    result = network.solve_ivp([0, 1, 0, 1], max_t=20)
    result_data = np.delete(result.y, 2, axis=0)
    min_size = min(data.shape[1], result_data.shape[1])
    return (data[:, :min_size] - result_data[:, :min_size]).flatten()


optimized_population = []
max_runs = 200
for i in range(max_runs):
    print(f'Run {i+1}/{max_runs}')
    optimized = least_squares(f, x0=np.random.rand(3))
    optimized_population.append(optimized.x)

Run 1/200
Run 2/200
Run 3/200
Run 4/200
Run 5/200
Run 6/200
Run 7/200
Run 8/200
Run 9/200
Run 10/200
Run 11/200
Run 12/200
Run 13/200
Run 14/200
Run 15/200
Run 16/200
Run 17/200
Run 18/200
Run 19/200
Run 20/200
Run 21/200
Run 22/200
Run 23/200
Run 24/200
Run 25/200
Run 26/200
Run 27/200
Run 28/200
Run 29/200
Run 30/200
Run 31/200
Run 32/200
Run 33/200
Run 34/200
Run 35/200
Run 36/200
Run 37/200
Run 38/200
Run 39/200
Run 40/200
Run 41/200
Run 42/200
Run 43/200
Run 44/200
Run 45/200
Run 46/200
Run 47/200
Run 48/200
Run 49/200
Run 50/200
Run 51/200
Run 52/200
Run 53/200
Run 54/200
Run 55/200
Run 56/200
Run 57/200
Run 58/200
Run 59/200
Run 60/200
Run 61/200
Run 62/200
Run 63/200
Run 64/200
Run 65/200
Run 66/200
Run 67/200
Run 68/200
Run 69/200
Run 70/200
Run 71/200
Run 72/200
Run 73/200
Run 74/200
Run 75/200
Run 76/200
Run 77/200
Run 78/200
Run 79/200
Run 80/200
Run 81/200
Run 82/200
Run 83/200
Run 84/200
Run 85/200
Run 86/200
Run 87/200
Run 88/200
Run 89/200
Run 90/200
Run 91/200
Run 92/2

In [25]:
results = np.array(optimized_population)

In [42]:
%matplotlib tk
fig, axs = plt.subplots(1, 3)
for i in range(3):
    axs[i].hist(results[:, i])
    axs[i].title.set_text(f'${network.rate_names[i]}$')

ValueError: Key backend: 'gtkagg' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

In [27]:
np.mean(results, axis=0)

array([2.35111011, 3.7481206 , 2.8798139 ])

In [28]:
np.std(results, axis=0)

array([1.26371969e-03, 3.53396534e-03, 5.76746749e-05])

In [26]:
params

array([2.38420773, 3.83905267, 2.95569299])